baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Georges Dietrich - Portfolio'
theme = 'toha'

[params]
  author = "Georges Dietrich"
  description = "Étudiant DevOps | Développeur Web Fullstack Flutter"
  profileImage = "images/profile.jpg"  # Assurez-vous que cette image existe dans le dossier /static/images/
  github = "https://github.com/lakrim92"
  email = "gdietrich@live.fr"
  phone = "0788478222"
  location = "Paris, France"

[social]
  github = "https://github.com/lakrim92"
  linkedin = "https://www.linkedin.com/in/georges-dietrich-5ab82b14a/"
